import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { SessionProvider } from "../context/session-context";
import localFont from "next/font/local";
import Logo from "components/components/ui/logo";
import { GlowOverlay } from "../components/glow-overlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const matter = localFont({
  src: [
    {
      path: "./matter-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./matter-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-matter",
});

const teodor = localFont({
  src: "./teodor-light.ttf",
  weight: "300",
  style: "normal",
  variable: "--font-teodor",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${matter.className} ${matter.variable} ${teodor.variable} antialiased`}>
        <SessionProvider>
          <GlowOverlay />
          <header className="p-4 fixed top-0 left-0 right-0 z-20 bg-transparent border-b border-gray-200/50 backdrop-blur-sm">
            <nav className="flex gap-4 py-2">
              <Logo color="black" className="h-6" />
            </nav>
          </header>
          <main className="pt-16 h-screen">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
