import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { SessionProvider } from "../context/SessionContext";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const matter = localFont({
  src: [
    {
      path: "./matter-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./matter-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

const teodor = localFont({
  src: "./teodor-light.ttf",
  weight: "300",
  style: "normal",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${matter.className} ${teodor.className} antialiased`}>
        <SessionProvider>
          <header className="p-4 fixed top-0 left-0 right-0 z-10 bg-background/80 backdrop-blur-sm border-b">
            <nav className="flex gap-4">
              <Link href="/" className="hover:underline">
                Home
              </Link>
              <Link href="/about" className="hover:underline">
                About
              </Link>
              <Link href="/settings" className="hover:underline">
                Settings
              </Link>
            </nav>
          </header>
          <main className="pt-16 h-screen">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
