[build]
builder = "NIXPACKS"
watchPatterns = ["frontend/**"]

[build.env]
NODE_VERSION = "18"

[deploy]
startCommand = "npm run start"
workingDirectory = "frontend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = 3000